wandb_version: 1

headless:
  desc: null
  value: true
save_final_state:
  desc: null
  value: true
early_stop:
  desc: null
  value: false
action_freq:
  desc: null
  value: 24
init_state:
  desc: null
  value: has_pokedex_nballs.state
max_steps:
  desc: null
  value: 20480
print_rewards:
  desc: null
  value: true
save_video:
  desc: null
  value: false
fast_video:
  desc: null
  value: true
session_path:
  desc: null
  value: session_33986c67
gb_path:
  desc: null
  value: PokemonRed.gb
debug:
  desc: null
  value: false
sim_frame_dist:
  desc: null
  value: 2000000.0
use_screen_explore:
  desc: null
  value: true
reward_scale:
  desc: null
  value: 4
extra_buttons:
  desc: null
  value: false
explore_weight:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    code_path: code/baselines/run_baseline_parallel_fast.py
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703043431.236769
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 14
      - 16
      - 22
      - 23
      - 35
      4: 3.10.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 81920000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1703043437249908894
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: session_33986c67
_last_obs:
  desc: null
  value: "[[[[  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [\
    \  0   0   0 ...   0   0   0]\n   ...\n   [  0   0   0 ...   0   0   0]\n   [\
    \  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]]\n\n  [[255 255\
    \ 255 ...   0   0   0]\n   [255 255 255 ...   0   0   0]\n   [255 255 255 ...\
    \   0   0   0]\n   ...\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...\
    \   0   0   0]\n   [  0   0   0 ...   0   0   0]]\n\n  [[  0   0   0 ...   0 \
    \  0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n\
    \   ...\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n\
    \   [  0   0   0 ...   0   0   0]]]\n\n\n [[[  0   0   0 ...   0   0   0]\n  \
    \ [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   ...\n  \
    \ [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0   0\
    \   0 ...   0   0   0]]\n\n  [[255 255 255 ...   0   0   0]\n   [255 255 255 ...\
    \   0   0   0]\n   [255 255 255 ...   0   0   0]\n   ...\n   [  0   0   0 ...\
    \   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0\
    \   0]]\n\n  [[  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n\
    \   [  0   0   0 ...   0   0   0]\n   ...\n   [  0   0   0 ...   0   0   0]\n\
    \   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]]]\n\n\n [[[\
    \  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0   0 \
    \  0 ...   0   0   0]\n   ...\n   [  0   0   0 ...   0   0   0]\n   [  0   0 \
    \  0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]]\n\n  [[255 255 255 ...\
    \   0   0   0]\n   [255 255 255 ...   0   0   0]\n   [255 255 255 ...   0   0\
    \   0]\n   ...\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0\
    \   0]\n   [  0   0   0 ...   0   0   0]]\n\n  [[  0   0   0 ...   0   0   0]\n\
    \   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   ...\n\
    \   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0 \
    \  0   0 ...   0   0   0]]]\n\n\n [[[  0   0   0 ...   0   0   0]\n   [  0   0\
    \   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   ...\n   [  0   0\
    \   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...\
    \   0   0   0]]\n\n  [[255 255 255 ...   0   0   0]\n   [255 255 255 ...   0 \
    \  0   0]\n   [255 255 255 ...   0   0   0]\n   ...\n   [  0   0   0 ...   0 \
    \  0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]]\n\
    \n  [[  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0\
    \   0   0 ...   0   0   0]\n   ...\n   [  0   0   0 ...   0   0   0]\n   [  0\
    \   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]]]]"
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object
    at 0x7fc4dc4ae470>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(0, 255, (3, 128, 40), uint8)
action_space:
  desc: null
  value: Discrete(6)
n_envs:
  desc: null
  value: 4
n_steps:
  desc: null
  value: 2560
gamma:
  desc: null
  value: 0.998
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 128
n_epochs:
  desc: null
  value: 3
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fc4db392d40>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fc4db392c20>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7fc4db33c130>
policy:
  desc: null
  value: "ActorCriticCnnPolicy(\n  (features_extractor): NatureCNN(\n    (cnn): Sequential(\n\
    \      (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n      (1): ReLU()\n\
    \      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))\n      (3): ReLU()\n\
    \      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))\n      (5): ReLU()\n\
    \      (6): Flatten(start_dim=1, end_dim=-1)\n    )\n    (linear): Sequential(\n\
    \      (0): Linear(in_features=768, out_features=512, bias=True)\n      (1): ReLU()\n\
    \    )\n  )\n  (pi_features_extractor): NatureCNN(\n    (cnn): Sequential(\n \
    \     (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n      (1): ReLU()\n\
    \      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))\n      (3): ReLU()\n\
    \      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))\n      (5): ReLU()\n\
    \      (6): Flatten(start_dim=1, end_dim=-1)\n    )\n    (linear): Sequential(\n\
    \      (0): Linear(in_features=768, out_features=512, bias=True)\n      (1): ReLU()\n\
    \    )\n  )\n  (vf_features_extractor): NatureCNN(\n    (cnn): Sequential(\n \
    \     (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n      (1): ReLU()\n\
    \      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))\n      (3): ReLU()\n\
    \      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))\n      (5): ReLU()\n\
    \      (6): Flatten(start_dim=1, end_dim=-1)\n    )\n    (linear): Sequential(\n\
    \      (0): Linear(in_features=768, out_features=512, bias=True)\n      (1): ReLU()\n\
    \    )\n  )\n  (mlp_extractor): MlpExtractor(\n    (policy_net): Sequential()\n\
    \    (value_net): Sequential()\n  )\n  (action_net): Linear(in_features=512, out_features=6,\
    \ bias=True)\n  (value_net): Linear(in_features=512, out_features=1, bias=True)\n\
    )"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fc4db3a26b0>
